name: de372

dependencies:
  - earthkit-data
  - ipykernel
  - ipyleaflet
  - jupyter
  - mapclassify
  - leafmap
  - localtileserver
  - python==3.11
  - solara
  - pip
  - pip:
    - earthkit
    - git+https://github.com/Deltares-research/FloodAdapt.git@76ab1805425aca6496e38529e7e1c404f08b9e26
    - lxml
    - conflator
    - -e .